class CfgPatches
{
	class example_retexture_config
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR"
		};
	};
};
class CfgVehicleClasses
{
	class Meaty_MenSnow
	{
		displayName="M_Men (Snow)";
	};
};
class CfgVehicles
{
	class B_Soldier_base_F;
	class B_Carryall_Base;
	class Meaty_Soldier_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Rifleman";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		backpack="Meaty_Carryall_Snow_B";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
	};
	class Meaty_Medic_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Medic";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		backpack="Meaty_Carryall_Snow_med_B";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
	};
	class Meaty_teamlead_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Team leader";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		backpack="Meaty_Carryall_Snow_TL_B";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MXGL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MXGL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
	};
	class Meaty_squadlead_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Squad leader";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		backpack="Meaty_Carryall_Snow_SL_B";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MXGL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MXGL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
	};
	class Meaty_AT_NLAW_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Rifleman (AT)";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		backpack="Meaty_Carryall_Snow_AT_B";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"launch_NLAW_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"launch_NLAW_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
	};
	class Meaty_AR_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Automatic Rifleman";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		backpack="Meaty_Carryall_Snow_AR_B";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MXSW_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MXSW_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer",
			"100Rnd_65x39_caseless_mag_Tracer"
		};
	};
	class Meaty_Crew_B_Sn: B_Soldier_base_F
	{
		author="Meatshield";
		_generalMacro="B_Soldier_F";
		scope=2;
		displayName="Crewman";
		vehicleClass="Meaty_MenSnow";
		nakedUniform="U_BasicBody";
		uniformClass="Blue_Snow_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_camo_co.paa"
		};
		linkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Blue_Snow_Vest",
			"Blue_Snow_Helmet",
			"Meaty_NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		weapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Meaty_MX_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag"
		};
	};
	class Meaty_Carryall_Snow_B_Base: B_Carryall_Base
	{
		scope=2;
		author="Meatshield";
		displayName="Backpack_Snow_B";
		picture="\A3\Weapons_F\Ammoboxes\Bags\data\UI\icon_B_C_Tortila_hex.paa";
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_backpack_co.paa"
		};
	};
	class Meaty_Carryall_Snow_B: Meaty_Carryall_Snow_B_Base
	{
		scope=1;
		class TransportMagazines
		{
			class 16Rnd_9x21_Mag
			{
				magazine="16Rnd_9x21_Mag";
				count=2;
			};
			class GrenadeHand
			{
				magazine="HandGrenade";
				count=2;
			};
		};
	};
	class Meaty_Carryall_Snow_med_B: Meaty_Carryall_Snow_B_Base
	{
		scope=1;
		class TransportMagazines
		{
			class SmokeShell
			{
				magazine="SmokeShell";
				count=4;
			};
		};
		class TransportItems
		{
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=10;
			};
		};
	};
	class Meaty_Carryall_Snow_TL_B: Meaty_Carryall_Snow_B_Base
	{
		scope=1;
		class TransportMagazines
		{
			class SmokeShell
			{
				magazine="SmokeShell";
				count=4;
			};
			class G_40mm_HE
			{
				magazine="3Rnd_HE_Grenade_shell";
				count=4;
			};
		};
	};
	class Meaty_Carryall_Snow_SL_B: Meaty_Carryall_Snow_B_Base
	{
		scope=1;
		class TransportMagazines
		{
			class SmokeShell
			{
				magazine="SmokeShell";
				count=3;
			};
			class G_40mm_HE
			{
				magazine="3Rnd_HE_Grenade_shell";
				count=4;
			};
			class G_40mm_Smoke
			{
				magazine="3Rnd_Smoke_Grenade_shell";
				count=4;
			};
		};
	};
	class Meaty_Carryall_Snow_AT_B: Meaty_Carryall_Snow_B_Base
	{
		scope=1;
		class TransportMagazines
		{
			class SmokeShell
			{
				magazine="SmokeShell";
				count=3;
			};
			class M_NLAW_AT_F
			{
				magazine="NLAW_F";
				count=2;
			};
		};
	};
	class Meaty_Carryall_Snow_AR_B: Meaty_Carryall_Snow_B_Base
	{
		scope=1;
		class TransportMagazines
		{
			class GrenadeHand
			{
				magazine="HandGrenade";
				count=4;
			};
			class B_65x39_Caseless
			{
				magazine="100Rnd_65x39_caseless_mag_Tracer";
				count=4;
			};
			class 16Rnd_9x21_Mag
			{
				magazine="16Rnd_9x21_Mag";
				count=6;
			};
		};
	};
};
class cfgWeapons
{
	class Uniform_Base;
	class UniformItem;
	class Blue_Snow_Camo: Uniform_Base
	{
		scope=2;
		displayName="Blue_Snow_Camo";
		picture="\A3\characters_f\data\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="Meaty_Soldier_B_Sn";
			containerClass="Supply20";
			mass=80;
		};
	};
	class ItemCore;
	class HeadgearItem;
	class Blue_Snow_Helmet: ItemCore
	{
		scope=2;
		weaponPoolAvailable=1;
		displayName="Blue_Snow_Helmet";
		picture="\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		model="\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_equip_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=100;
			uniformModel="\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
		};
	};
	class Vest_Camo_Base;
	class VestItem;
	class Blue_Snow_Vest: Vest_Camo_Base
	{
		scope=2;
		displayName="Blue_Snow_Vest";
		picture="\A3\characters_f\Data\UI\icon_V_plate_carrier_1_ca.paa";
		model="\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Meaty_Blu_Snow\Data\blu_snow_vest_co.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\A3\Characters_F\BLUFOR\equip_b_vest02";
			containerClass="Supply100";
			mass=50;
			armor="5*0.5";
			passThrough=0.69999999;
			hiddenSelections[]=
			{
				"camo"
			};
		};
	};
	class NVGoggles;
	class ItemInfo;
	class Meaty_NVGoggles: NVGoggles
	{
		modelOptics="\A3\weapons_f\reticle\optics_night";
		model="\A3\Weapons_f\binocular\nvg_proxy";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f\common\data\nvg_opfor_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="A3\weapons_f\binocular\nvg_proxy.p3d";
			modelOff="A3\weapons_f\binocular\NVG_proxy_off.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
		};
	};
	class arifle_MX_Black_F;
	class Meaty_MX_Hamr_pointer_F: arifle_MX_Black_F
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_Hamr";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class arifle_MX_GL_Black_F;
	class Meaty_MXGL_Hamr_pointer_F: arifle_MX_GL_Black_F
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_Hamr";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class arifle_MX_SW_Black_F;
	class Meaty_MXSW_Hamr_pointer_F: arifle_MX_SW_Black_F
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_Hamr";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
};
